package urender.demo.editor;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import urender.api.UTextureMagFilter;
import urender.api.UTextureMinFilter;
import urender.api.UTextureWrap;
import urender.engine.UTextureMapper;

public class TextureMapperEditor extends javax.swing.JPanel {

	/**
	 * Creates new form TextureMapperEditor
	 */
	public TextureMapperEditor() {
		initComponents();

		loadEnumComboBox(UTextureWrap.values(), wrapU, wrapV);
		loadEnumComboBox(UTextureMagFilter.values(), magFilter);
		loadEnumComboBox(UTextureMinFilter.values(), minFilter);
	}
	
	public JTextField getNameEditField() {
		return samplerName;
	}

	private void loadEnumComboBox(Enum[] values, JComboBox... boxes) {
		for (JComboBox box : boxes) {
			for (Enum e : values) {
				box.addItem(e.name());
			}
		}
	}

	public void load(TextureMapperEditHandle handle) {
		UTextureMapper mapper = handle.mapper;
		samplerName.setText(mapper.getShaderVariableName());
		texture.setModel(handle.textureSelect);
		wrapU.setSelectedItem(mapper.getWrapU().name());
		wrapV.setSelectedItem(mapper.getWrapV().name());
		magFilter.setSelectedItem(mapper.getMagFilter().name());
		minFilter.setSelectedItem(mapper.getMinFilter().name());
	}
	
	public void save(TextureMapperEditHandle handle) {
		UTextureMapper mapper = handle.mapper;
		TextureEditHandle texhnd = handle.textureSelect.getSelectedItem();
		mapper.setTexture(texhnd == null ? null : texhnd.tex);
		mapper.setWrapU(UTextureWrap.values()[wrapU.getSelectedIndex()]);
		mapper.setWrapV(UTextureWrap.values()[wrapV.getSelectedIndex()]);
		mapper.setMagFilter(UTextureMagFilter.values()[magFilter.getSelectedIndex()]);
		mapper.setMinFilter(UTextureMinFilter.values()[minFilter.getSelectedIndex()]);
		mapper.setShaderVariableName(getNowSamplerName());
	}
	
	public String getNowSamplerName() {
		return getDocText(samplerName.getDocument());
	}
	
	private static String getDocText(Document doc) {
		try {
			return doc.getText(0, doc.getLength());
		} catch (BadLocationException ex) {
			Logger.getLogger(TextureMapperEditor.class.getName()).log(Level.SEVERE, null, ex);
		}
		return null;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        samplerNameLabel = new javax.swing.JLabel();
        samplerName = new javax.swing.JTextField();
        paramsPanel = new javax.swing.JPanel();
        wrapModeLabel = new javax.swing.JLabel();
        wrapULabel = new javax.swing.JLabel();
        wrapU = new javax.swing.JComboBox<>();
        wrapVLabel = new javax.swing.JLabel();
        wrapV = new javax.swing.JComboBox<>();
        filteringLabel = new javax.swing.JLabel();
        magFilterLabel = new javax.swing.JLabel();
        magFilter = new javax.swing.JComboBox<>();
        minFilterLabel = new javax.swing.JLabel();
        minFilter = new javax.swing.JComboBox<>();
        textureLabel = new javax.swing.JLabel();
        texture = new javax.swing.JComboBox<>();

        samplerNameLabel.setText("Sampler name");

        paramsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters"));

        wrapModeLabel.setText("Wrap mode");

        wrapULabel.setText("U");

        wrapVLabel.setText("V");

        filteringLabel.setText("Filtering");

        magFilterLabel.setText("Magnification");

        minFilterLabel.setText("Minification");

        javax.swing.GroupLayout paramsPanelLayout = new javax.swing.GroupLayout(paramsPanel);
        paramsPanel.setLayout(paramsPanelLayout);
        paramsPanelLayout.setHorizontalGroup(
            paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paramsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wrapModeLabel)
                    .addComponent(filteringLabel)
                    .addGroup(paramsPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paramsPanelLayout.createSequentialGroup()
                                .addComponent(magFilterLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(magFilter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(paramsPanelLayout.createSequentialGroup()
                                .addComponent(wrapULabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wrapU, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wrapVLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wrapV, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(minFilterLabel)))
                    .addComponent(minFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paramsPanelLayout.setVerticalGroup(
            paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paramsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wrapModeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wrapULabel)
                    .addComponent(wrapU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrapVLabel)
                    .addComponent(wrapV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filteringLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(magFilterLabel)
                    .addComponent(magFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minFilterLabel)
                    .addComponent(minFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textureLabel.setText("Texture");

        texture.setMaximumRowCount(20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paramsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(samplerNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(samplerName))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(textureLabel)
                                .addGap(39, 39, 39)
                                .addComponent(texture, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(samplerNameLabel)
                    .addComponent(samplerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textureLabel)
                    .addComponent(texture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filteringLabel;
    private javax.swing.JComboBox<String> magFilter;
    private javax.swing.JLabel magFilterLabel;
    private javax.swing.JComboBox<String> minFilter;
    private javax.swing.JLabel minFilterLabel;
    private javax.swing.JPanel paramsPanel;
    private javax.swing.JTextField samplerName;
    private javax.swing.JLabel samplerNameLabel;
    private javax.swing.JComboBox<TextureEditHandle> texture;
    private javax.swing.JLabel textureLabel;
    private javax.swing.JLabel wrapModeLabel;
    private javax.swing.JComboBox<String> wrapU;
    private javax.swing.JLabel wrapULabel;
    private javax.swing.JComboBox<String> wrapV;
    private javax.swing.JLabel wrapVLabel;
    // End of variables declaration//GEN-END:variables
}
