package urender.demo.perf;

public class PerfMonitorWindow extends javax.swing.JFrame implements IPerfMonitor {

	/**
	 * Creates new form PerfMonitorWindow
	 */
	public PerfMonitorWindow() {
		initComponents();
	}

	private long lastFrametime = 0;

	@Override
	public void newFrame() {
		long frametime = System.currentTimeMillis();

		int fps;
		if (lastFrametime == 0) {
			fps = 0;
		} else {
			long diff = frametime - lastFrametime;
			fps = (int) (1000 / diff);
			fpsGraph.update(fps);
			framerateText.setText(fps + " FPS");
		}
		lastFrametime = frametime;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fpsGraph = new urender.demo.perf.PerfMonitorGraphSurface();
        separator = new javax.swing.JSeparator();
        framerateLabel = new javax.swing.JLabel();
        framerateText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Performance monitor");

        javax.swing.GroupLayout fpsGraphLayout = new javax.swing.GroupLayout(fpsGraph);
        fpsGraph.setLayout(fpsGraphLayout);
        fpsGraphLayout.setHorizontalGroup(
            fpsGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fpsGraphLayout.setVerticalGroup(
            fpsGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        framerateLabel.setText("Framerate:");

        framerateText.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fpsGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separator)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(framerateLabel)
                        .addGap(18, 18, 18)
                        .addComponent(framerateText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 232, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(framerateLabel)
                    .addComponent(framerateText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fpsGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private urender.demo.perf.PerfMonitorGraphSurface fpsGraph;
    private javax.swing.JLabel framerateLabel;
    private javax.swing.JLabel framerateText;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
