/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urender.demo.debug;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.joml.Vector3f;
import urender.scenegraph.UDirectionalLight;
import urender.scenegraph.ULight;
import urender.scenegraph.UPointLight;
import urender.scenegraph.UScene;
import urender.scenegraph.USpotLight;

public class RTLI extends javax.swing.JFrame {

	/**
	 * Creates new form RTLI
	 */
	public RTLI() {
		initComponents();
		
		spotCutoff.addChangeListener(new ChangeListener() {
			@Override
			public void stateChanged(ChangeEvent e) {
				USpotLight spot = (USpotLight) spotLightBox.getSelectedItem();
				if (spot != null) {
					spot.cutoffAngleDeg = spotCutoff.getValue();
				}
			}
		});
		spotDir.addListener(new VectorEditorListener() {
			@Override
			public void onChanged() {
				spotDirDisp.setText(vecToStr(spotDir.getVector()));
			}
		});
	}
	
	private String vecToStr(Vector3f vec) {
		return "(" + vec.x + ", " + vec.y + ", " + vec.z + ")";
	}
	
	public void loadScene(UScene scene) {
		dirLampsBox.removeAllItems();
		pointLightsBox.removeAllItems();
		spotLightBox.removeAllItems();
		for (ULight light : scene.lights) {
			switch (light.getLightType()) {
				case DIRECTIONAL:
					dirLampsBox.addItem((UDirectionalLight) light);
					break;
				case POINT:
					pointLightsBox.addItem((UPointLight) light);
					break;
				case SPOT:
					spotLightBox.addItem((USpotLight) light);
					break;
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lightTypeTabs = new javax.swing.JTabbedPane();
        dirLightEditor = new javax.swing.JPanel();
        dirLampsBox = new javax.swing.JComboBox<>();
        dirLightDirLabel = new javax.swing.JLabel();
        dirLightDir = new urender.demo.debug.DirectionalVec3fSliderEditor();
        dirLightColorsPanel = new javax.swing.JPanel();
        dirLightColors = new urender.demo.debug.LightColorEditorPanel();
        pointLightEditor = new javax.swing.JPanel();
        pointLightsBox = new javax.swing.JComboBox<>();
        pointPosLabel = new javax.swing.JLabel();
        pointPos = new urender.demo.debug.Vec3fEditor();
        pointAttnPanel = new javax.swing.JPanel();
        pointAttn = new urender.demo.debug.LightAttenuationEditor();
        pointColorPanel = new javax.swing.JPanel();
        pointLightColors = new urender.demo.debug.LightColorEditorPanel();
        spotLightEditor = new javax.swing.JPanel();
        spotLightBox = new javax.swing.JComboBox<>();
        spotColorPanel = new javax.swing.JPanel();
        spotLightColors = new urender.demo.debug.LightColorEditorPanel();
        spotPosLabel = new javax.swing.JLabel();
        spotPos = new urender.demo.debug.Vec3fEditor();
        spotAttnPanel = new javax.swing.JPanel();
        spotAttn = new urender.demo.debug.LightAttenuationEditor();
        spotDir = new urender.demo.debug.DirectionalVec3fSliderEditor();
        spotDirLabel = new javax.swing.JLabel();
        spotCutoffLabel = new javax.swing.JLabel();
        spotCutoff = new javax.swing.JSlider();
        spotDirDisp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("uRTLI");

        dirLampsBox.setMaximumRowCount(16);
        dirLampsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirLampsBoxActionPerformed(evt);
            }
        });

        dirLightDirLabel.setText("Direction:");

        dirLightColorsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));

        javax.swing.GroupLayout dirLightColorsPanelLayout = new javax.swing.GroupLayout(dirLightColorsPanel);
        dirLightColorsPanel.setLayout(dirLightColorsPanelLayout);
        dirLightColorsPanelLayout.setHorizontalGroup(
            dirLightColorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirLightColorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dirLightColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dirLightColorsPanelLayout.setVerticalGroup(
            dirLightColorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirLightColorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dirLightColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dirLightEditorLayout = new javax.swing.GroupLayout(dirLightEditor);
        dirLightEditor.setLayout(dirLightEditorLayout);
        dirLightEditorLayout.setHorizontalGroup(
            dirLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirLightEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dirLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dirLampsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dirLightDir, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGroup(dirLightEditorLayout.createSequentialGroup()
                        .addComponent(dirLightDirLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dirLightColorsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dirLightEditorLayout.setVerticalGroup(
            dirLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dirLightEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dirLampsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dirLightDirLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dirLightDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dirLightColorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lightTypeTabs.addTab("Directional lamps", dirLightEditor);

        pointLightsBox.setMaximumRowCount(16);
        pointLightsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointLightsBoxActionPerformed(evt);
            }
        });

        pointPosLabel.setText("Position");

        pointAttnPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Attenuation"));

        javax.swing.GroupLayout pointAttnPanelLayout = new javax.swing.GroupLayout(pointAttnPanel);
        pointAttnPanel.setLayout(pointAttnPanelLayout);
        pointAttnPanelLayout.setHorizontalGroup(
            pointAttnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointAttnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointAttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pointAttnPanelLayout.setVerticalGroup(
            pointAttnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointAttnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointAttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pointColorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));

        javax.swing.GroupLayout pointColorPanelLayout = new javax.swing.GroupLayout(pointColorPanel);
        pointColorPanel.setLayout(pointColorPanelLayout);
        pointColorPanelLayout.setHorizontalGroup(
            pointColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointColorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointLightColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pointColorPanelLayout.setVerticalGroup(
            pointColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointColorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointLightColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pointLightEditorLayout = new javax.swing.GroupLayout(pointLightEditor);
        pointLightEditor.setLayout(pointLightEditorLayout);
        pointLightEditorLayout.setHorizontalGroup(
            pointLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointLightEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pointLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pointLightsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pointLightEditorLayout.createSequentialGroup()
                        .addGroup(pointLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pointPosLabel)
                            .addComponent(pointPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pointAttnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pointColorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pointLightEditorLayout.setVerticalGroup(
            pointLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointLightEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointLightsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pointPosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pointPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pointAttnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pointColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lightTypeTabs.addTab("Point lights", pointLightEditor);

        spotLightBox.setMaximumRowCount(16);
        spotLightBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spotLightBoxActionPerformed(evt);
            }
        });

        spotColorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));

        javax.swing.GroupLayout spotColorPanelLayout = new javax.swing.GroupLayout(spotColorPanel);
        spotColorPanel.setLayout(spotColorPanelLayout);
        spotColorPanelLayout.setHorizontalGroup(
            spotColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spotColorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spotLightColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        spotColorPanelLayout.setVerticalGroup(
            spotColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spotColorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spotLightColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spotPosLabel.setText("Position");

        spotAttnPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Attenuation"));

        javax.swing.GroupLayout spotAttnPanelLayout = new javax.swing.GroupLayout(spotAttnPanel);
        spotAttnPanel.setLayout(spotAttnPanelLayout);
        spotAttnPanelLayout.setHorizontalGroup(
            spotAttnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spotAttnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spotAttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        spotAttnPanelLayout.setVerticalGroup(
            spotAttnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spotAttnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spotAttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        spotDirLabel.setText("Spotlight direction");

        spotCutoffLabel.setText("Cutoff");

        spotCutoff.setMajorTickSpacing(20);
        spotCutoff.setMaximum(180);
        spotCutoff.setMinorTickSpacing(10);
        spotCutoff.setPaintLabels(true);
        spotCutoff.setPaintTicks(true);
        spotCutoff.setValue(90);

        spotDirDisp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        spotDirDisp.setText("-");

        javax.swing.GroupLayout spotLightEditorLayout = new javax.swing.GroupLayout(spotLightEditor);
        spotLightEditor.setLayout(spotLightEditorLayout);
        spotLightEditorLayout.setHorizontalGroup(
            spotLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spotLightEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spotLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spotLightBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spotColorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spotAttnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spotDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(spotLightEditorLayout.createSequentialGroup()
                        .addGroup(spotLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spotPosLabel)
                            .addComponent(spotPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spotDirLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(spotLightEditorLayout.createSequentialGroup()
                        .addComponent(spotCutoffLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spotCutoff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, spotLightEditorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(spotDirDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        spotLightEditorLayout.setVerticalGroup(
            spotLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spotLightEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spotLightBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spotPosLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spotPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spotDirLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spotDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spotDirDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spotLightEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spotCutoffLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spotCutoff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spotAttnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spotColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lightTypeTabs.addTab("Spotlights", spotLightEditor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lightTypeTabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lightTypeTabs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dirLampsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirLampsBoxActionPerformed
		UDirectionalLight dirLight = (UDirectionalLight) dirLampsBox.getSelectedItem();
		if (dirLight != null) {
			dirLightDir.loadVec(dirLight.direction);
			dirLightColors.load(dirLight.colors);
		}
		else {
			dirLightDir.loadVec(null);
			dirLightColors.load(null);
		}
    }//GEN-LAST:event_dirLampsBoxActionPerformed

    private void pointLightsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointLightsBoxActionPerformed
        UPointLight pointLight = (UPointLight) pointLightsBox.getSelectedItem();
		if (pointLight != null) {
			pointPos.loadVec(pointLight.position);
			pointAttn.load(pointLight);
			pointLightColors.load(pointLight.colors);
		}
		else {
			pointPos.loadVec(null);
			pointAttn.load(null);
			pointLightColors.load(null);
		}
    }//GEN-LAST:event_pointLightsBoxActionPerformed

    private void spotLightBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spotLightBoxActionPerformed
		USpotLight spotLight = (USpotLight) spotLightBox.getSelectedItem();
		if (spotLight != null) {
			spotPos.loadVec(spotLight.position);
			spotDir.loadVec(spotLight.spotDirection);
			spotAttn.load(spotLight);
			spotLightColors.load(spotLight.colors);
			spotCutoff.setValue((int)spotLight.cutoffAngleDeg);
		}
		else {
			spotPos.loadVec(null);
			spotDir.loadVec(null);
			spotAttn.load(null);
			spotLightColors.load(null);
			spotCutoff.setValue(90);
		}
    }//GEN-LAST:event_spotLightBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<UDirectionalLight> dirLampsBox;
    private urender.demo.debug.LightColorEditorPanel dirLightColors;
    private javax.swing.JPanel dirLightColorsPanel;
    private urender.demo.debug.DirectionalVec3fSliderEditor dirLightDir;
    private javax.swing.JLabel dirLightDirLabel;
    private javax.swing.JPanel dirLightEditor;
    private javax.swing.JTabbedPane lightTypeTabs;
    private urender.demo.debug.LightAttenuationEditor pointAttn;
    private javax.swing.JPanel pointAttnPanel;
    private javax.swing.JPanel pointColorPanel;
    private urender.demo.debug.LightColorEditorPanel pointLightColors;
    private javax.swing.JPanel pointLightEditor;
    private javax.swing.JComboBox<UPointLight> pointLightsBox;
    private urender.demo.debug.Vec3fEditor pointPos;
    private javax.swing.JLabel pointPosLabel;
    private urender.demo.debug.LightAttenuationEditor spotAttn;
    private javax.swing.JPanel spotAttnPanel;
    private javax.swing.JPanel spotColorPanel;
    private javax.swing.JSlider spotCutoff;
    private javax.swing.JLabel spotCutoffLabel;
    private urender.demo.debug.DirectionalVec3fSliderEditor spotDir;
    private javax.swing.JLabel spotDirDisp;
    private javax.swing.JLabel spotDirLabel;
    private javax.swing.JComboBox<UPointLight> spotLightBox;
    private urender.demo.debug.LightColorEditorPanel spotLightColors;
    private javax.swing.JPanel spotLightEditor;
    private urender.demo.debug.Vec3fEditor spotPos;
    private javax.swing.JLabel spotPosLabel;
    // End of variables declaration//GEN-END:variables
}
